server:
  port: 8083
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    enables: true
jwt:
  secret: EEpAkjtJ2CZgwlMTIKslTISf3/3NjabXPlHk6lB73ao=
  expirationMs: 86400000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url: http://localhost:8081/actuator/info
    health-check-url: http://localhost:8081/actuator/health
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
logging:
  level:
    org.springframework: INFO
    com.authService: DEBUG
  file:
    name: target/auth-service.log