server:
  port: 8082
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: gatewayDeptCB
                fallbackUri: forward:/fallback/departments
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: gatewayEmpCB
                fallbackUri: forward:/fallback/employees
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
jwt:
  secret: EEpAkjtJ2CZgwlMTIKslTISf3/3NjabXPlHk6lB73ao=
  expirationMs: 86400000
resilience4j:
  circuitbreaker:
    instances:
      gatewayDeptCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true
      gatewayEmpCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.default.svc.cluster.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    # hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    #status-page-url: http://localhost:8082/actuator/info
    #health-check-url: http://localhost:8082/actuator/health
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.cloud: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    io.github.resilience4j: DEBUG
    com.apiGateway: DEBUG
    com.apiGateway.apiGateway.security: TRACE
    org.slf4j: TRACE
  file:
    name: target/spring.log