server:
  port: 8080

spring:
  application:
    name: department-service
  datasource:
    url: jdbc:h2:mem:departmentdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
      path: /h2-console
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    enables: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url: http://localhost:8080/actuator/info
    health-check-url: http://localhost:8080/actuator/health
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    com.departmentService: DEBUG
    org.springframework.cloud: TRACE
    com.netflix.eureka: TRACE
    com.netflix.discovery: TRACE