server:
  port: 8081

spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:h2:mem:employeedb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
      department-service:
        connectTimeout: 5000
        readTimeout: 10000

resilience4j:
  circuitbreaker:
    instances:
      deptServiceCircuit:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 60000
        permittedNumberOfCallsInHalfOpenState: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url: http://localhost:8081/actuator/info
    health-check-url: http://localhost:8081/actuator/health
    instance-id: employee-service:${server.port}

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    com.EmployeeService: DEBUG
    org.springframework.cloud: TRACE
    com.netflix.eureka: TRACE
    com.netflix.discovery: TRACE